### ISSUE TITLE
please add a AUTHORS and LICENSE file

### ISSUE THREAD

**Issue by egonw** [Novartis/MoaBox#1]
Thank you for this wonderful data deposit! I would be very helpful if you could add an AUTHORS file (so that people know whom to acknowledge in a citation) and a LICENSE file (so that people know how they can reuse the data and how you want them to thank you (=attribution)).

**Comment by imoutsatsos** [comment]
Thank you. Indeed we are planning on adding these items. They are still in preparation

**Comment by imoutsatsos** [comment]
As License is not relevant for non-software files, I have added a copyright notice and link to the  preprint manuscript deposition that should be referenced.
